1. What is a Python library? Why do we use Python libraries?


A Python library is a collection of pre-written code modules that provide functionalities to accomplish specific tasks. These libraries contain reusable functions, classes, and constants that help developers avoid reinventing the wheel and accelerate the development process. Python libraries are created to address various needs such as data manipulation, web development, machine learning, scientific computing, and more.

We use Python libraries for several reasons:

Efficiency: Python libraries allow developers to leverage existing code rather than writing everything from scratch, which saves time and effort.

Functionality: Libraries provide specialized functionalities for specific tasks, such as data analysis, web scraping, or image processing, that would be complex or time-consuming to implement manually.

Reliability: Established Python libraries are often thoroughly tested and maintained by a community of developers, making them reliable and robust solutions for various tasks.

Performance: Many Python libraries are implemented in optimized languages like C or C++, which can provide better performance compared to pure Python code.

Interoperability: Python libraries often integrate well with each other and with other programming languages, allowing developers to combine functionalities from different sources seamlessly.

2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of data, but they have several differences:

Data Types: NumPy arrays are homogeneous, meaning they can only store elements of the same data type. This homogeneity allows for more efficient storage and operations on the data. In contrast, Python lists can store elements of different data types.

Memory Efficiency: NumPy arrays are more memory efficient compared to Python lists, especially for large datasets. This efficiency is due to the homogeneous nature of NumPy arrays and their fixed size, which reduces overhead.

Performance: NumPy arrays offer faster computation and mathematical operations compared to Python lists. NumPy is implemented in C and optimized for performance, whereas Python lists are interpreted and involve more overhead.

Functionality: NumPy arrays provide a wide range of mathematical functions and operations for numerical computing, such as matrix operations, linear algebra, Fourier transforms, and random number generation. Python lists offer more general-purpose functionalities, but they lack the extensive mathematical capabilities of NumPy.

Indexing and Slicing: Both NumPy arrays and Python lists support indexing and slicing. However, NumPy arrays offer more advanced indexing techniques, such as boolean indexing, fancy indexing, and multidimensional slicing, which can be more convenient for array-oriented programming tasks.

Mutability: Python lists are mutable, meaning you can modify the elements after creation (e.g., add or remove elements). In contrast, NumPy arrays are immutable; once created, their size and data type cannot be changed. However, you can modify the elements of a NumPy array.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


The given array is a 2-dimensional array (often referred to as a matrix) with 3 rows and 4 columns. To find its shape, size, and dimensions:

Shape: The shape of an array represents the number of elements along each dimension. For this array, the shape is (3, 4), indicating 3 rows and 4 columns.

Size: The size of an array is the total number of elements it contains. In this case, the size is the product of the dimensions, so it's 3 (rows) * 4 (columns) = 12.

Dimensions: The number of dimensions of an array is also called its rank. Since this array has rows and columns, it is a 2-dimensional array.

So, to summarize:

Shape: (3, 4)

Size: 12

Dimensions: 2

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the first row using slicing
first_row = arr[0]

# Print the first row
print("First Row:", first_row)


First Row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = arr[2, 3]  # Indexing starts from 0, so row 3 is at index 2 and column 4 is at index 3

# Print the element
print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_elements = arr[:, 1::2]  # Start from index 1 (second column), and step by 2

# Print the odd-indexed elements
print("Odd-indexed elements:")
print(odd_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [4]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.random((3, 3))

# Print the random matrix
print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)


Random 3x3 matrix with values between 0 and 1:
[[0.80915374 0.26052548 0.10899525]
 [0.18581843 0.12163478 0.3095563 ]
 [0.27540669 0.40629026 0.93864243]]


8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand:

This function generates random numbers from a uniform distribution between 0 and 1.

It takes a variable number of arguments representing the shape of the output array.

If no arguments are provided, it returns a single random number.

Example:

In [5]:
import numpy as np
random_numbers = np.random.rand(3, 2)  # Generates a 3x2 array of random numbers between 0 and 1


np.random.randn:

This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1).

It takes a variable number of arguments representing the shape of the output array.

If no arguments are provided, it returns a single random number.

Example:

In [ ]:
import numpy as np
random_numbers = np.random.randn(3, 2)  # Generates a 3x2 array of random numbers from the standard normal distribution


9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
import numpy as np

# Define the original array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Increase the dimension of the array
expanded_array = np.expand_dims(original_array, axis=0)

# Print the original and expanded arrays
print("Original array:")
print(original_array)
print("\nExpanded array:")
print(expanded_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Expanded array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np

# Define the original array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Transpose the array using the transpose() function
transposed_array = np.transpose(original_array)

# Transpose the array using the T attribute
# transposed_array = original_array.T

# Print the original and transposed arrays
print("Original array:")
print(original_array)
print("\nTransposed array:")
print(transposed_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

These matrices both have dimensions 3x4, meaning they have 3 rows and 4 columns.

If you're asking about operations you can perform with these matrices, there are various operations possible such as addition, subtraction, multiplication, etc., depending on what you aim to achieve. For instance:

Addition: You can add Matrix A and Matrix B element-wise if they have the same shape.
Subtraction: You can subtract one matrix from another element-wise if they have the same shape.
Multiplication: You can perform matrix multiplication if the number of columns in the first matrix is equal to the number of rows in the second matrix.

12. Which function in Numpy can be used to swap the byte order of an array?

The function in Numpy that can be used to swap the byte order of an array is arr.byteswap ()1. This function returns a byteswapped array, optionally swapped in-place. It toggles between low-endian and big-endian data representation2.

1: numpy.ndarray.byteswap — NumPy v1.26 Manual 2: Byte-swapping — NumPy v1.26 Manual


13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function is a NumPy function that computes the (multiplicative) inverse of a square matrix. The inverse of a matrix A is another matrix B such that A * B = B * A = I, where I is the identity matrix. The inverse of a matrix can be used to solve systems of linear equations, find the determinant of a matrix, or perform other matrix operations12.

1: numpy.linalg.inv — NumPy

14. What ^oes the np.reshape function ^o, an^ how is it use^?

The np.reshape function is a NumPy function that changes the shape of an array without changing its data. It takes an array and a new shape as arguments, and returns a new array with the same data but with the specified shape. One of the shape dimensions can be -1, which means the value is inferred from the length of the array and the remaining dimensions12.

To use the np.reshape function, you can import NumPy as np and then call np.reshape(array, newshape, order=‘C’). The order argument specifies the index order for reading and writing the elements, which can be ‘C’ for C-like order, ‘F’ for Fortran-like order, or ‘A’ for Fortran-like order if the array is Fortran contiguous in memory, or C-like order otherwise2.

Here is an example of using the np.reshape function:

In [10]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]]) # a 2x3 array
b = np.reshape(a, 6) # a 1x6 array
c = np.reshape(a, (3, 2)) # a 3x2 array
d = np.reshape(a, (2, -1)) # a 2x3 array, -1 means inferred from the original shape
print(b)
print(c)
print(d)


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

Broadcasting is a feature of NumPy that allows you to perform arithmetic operations on arrays of different shapes, by automatically expanding the smaller array to match the larger one. Broadcasting makes it possible to vectorize array operations, which can improve the efficiency and readability of your code12.

For example, if you have an array a with shape (3, 4) and a scalar b, you can add them together as a + b, and NumPy will broadcast b to an array of shape (3, 4) with the same value in each element. Similarly, if you have an array c with shape (4,), you can add it to a as a + c, and NumPy will broadcast c to an array of shape (3, 4) by repeating it along the first axis.

However, broadcasting only works when the arrays have compatible shapes, which means that the size of each dimension must be either equal or one. If the arrays have incompatible shapes, NumPy will raise a ValueError exception3.

1: Broadcasting — NumPy v1.26 Manual 2: Numpy Broadcasting (With Examples) - Programiz 3: Broadcasting — NumPy v1.21 Manual